spring:
  h2:
    console.enabled: true
  application:
    name: to-do-list
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:file:~/to-do-list-db
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
server:
  port: 8081
